package overwatch

// PlayerRegion ...
type PlayerRegion struct {
	Stats struct {
		Quickplay struct {
			AverageStats struct {
			} `json:"average_stats"`
			GameStats struct {
				ReconAssistsMostInGame             float64 `json:"recon_assists_most_in_game"`
				Kpd                                float64 `json:"kpd"`
				SoloKillsMostInGame                float64 `json:"solo_kills_most_in_game"`
				TurretsDestroyedMostInGame         float64 `json:"turrets_destroyed_most_in_game"`
				HeroDamageDoneMostInGame           float64 `json:"hero_damage_done_most_in_game"`
				ShieldGeneratorDestroyedMostInGame float64 `json:"shield_generator_destroyed_most_in_game"`
				FinalBlows                         float64 `json:"final_blows"`
				Multikills                         float64 `json:"multikills"`
				DefensiveAssists                   float64 `json:"defensive_assists"`
				MedalsSilver                       float64 `json:"medals_silver"`
				TeleporterPadsDestroyed            float64 `json:"teleporter_pads_destroyed"`
				HeroDamageDone                     float64 `json:"hero_damage_done"`
				MedalsBronze                       float64 `json:"medals_bronze"`
				HealingDone                        float64 `json:"healing_done"`
				Cards                              float64 `json:"cards"`
				OffensiveAssists                   float64 `json:"offensive_assists"`
				Deaths                             float64 `json:"deaths"`
				TurretsDestroyed                   float64 `json:"turrets_destroyed"`
				SoloKills                          float64 `json:"solo_kills"`
				MedalsGold                         float64 `json:"medals_gold"`
				ObjectiveTimeMostInGame            float64 `json:"objective_time_most_in_game"`
				ObjectiveKillsMostInGame           float64 `json:"objective_kills_most_in_game"`
				MeleeFinalBlowsMostInGame          float64 `json:"melee_final_blows_most_in_game"`
				MultikillBest                      float64 `json:"multikill_best"`
				KillStreakBest                     float64 `json:"kill_streak_best"`
				TimeSpentOnFireMostInGame          float64 `json:"time_spent_on_fire_most_in_game"`
				EnvironmentalKills                 float64 `json:"environmental_kills"`
				GamesWon                           float64 `json:"games_won"`
				ReconAssists                       float64 `json:"recon_assists"`
				AllDamageDone                      float64 `json:"all_damage_done"`
				TimeSpentOnFire                    float64 `json:"time_spent_on_fire"`
				OffensiveAssistsMostInGame         float64 `json:"offensive_assists_most_in_game"`
				BarrierDamageDoneMostInGame        float64 `json:"barrier_damage_done_most_in_game"`
				Eliminations                       float64 `json:"eliminations"`
				TimePlayed                         float64 `json:"time_played"`
				ObjectiveKills                     float64 `json:"objective_kills"`
				AllDamageDoneMostInGame            float64 `json:"all_damage_done_most_in_game"`
				MeleeFinalBlows                    float64 `json:"melee_final_blows"`
				BarrierDamageDone                  float64 `json:"barrier_damage_done"`
				EnvironmentalKillMostInGame        float64 `json:"environmental_kill_most_in_game"`
				ShieldGeneratorDestroyed           float64 `json:"shield_generator_destroyed"`
				HealingDoneMostInGame              float64 `json:"healing_done_most_in_game"`
				DefensiveAssistsMostInGame         float64 `json:"defensive_assists_most_in_game"`
				ObjectiveTime                      float64 `json:"objective_time"`
				FinalBlowsMostInGame               float64 `json:"final_blows_most_in_game"`
				EliminationsMostInGame             float64 `json:"eliminations_most_in_game"`
				Medals                             float64 `json:"medals"`
			} `json:"game_stats"`
			Competitive         bool `json:"competitive"`
			RollingAverageStats struct {
				ObjectiveKills    float64 `json:"objective_kills"`
				SoloKills         float64 `json:"solo_kills"`
				HeroDamageDone    float64 `json:"hero_damage_done"`
				AllDamageDone     float64 `json:"all_damage_done"`
				HealingDone       float64 `json:"healing_done"`
				TimeSpentOnFire   float64 `json:"time_spent_on_fire"`
				Eliminations      float64 `json:"eliminations"`
				ObjectiveTime     float64 `json:"objective_time"`
				BarrierDamageDone float64 `json:"barrier_damage_done"`
				Deaths            float64 `json:"deaths"`
				FinalBlows        float64 `json:"final_blows"`
			} `json:"rolling_average_stats"`
			OverallStats struct {
				Level     int    `json:"level"`
				Losses    int    `json:"losses"`
				Tier      string `json:"tier"`
				RankImage string `json:"rank_image"`
				Prestige  int    `json:"prestige"`
				Comprank  int    `json:"comprank"`
				Avatar    string `json:"avatar"`
				WinRate   int    `json:"win_rate"`
				Games     int    `json:"games"`
				Wins      int    `json:"wins"`
			} `json:"overall_stats"`
		} `json:"quickplay"`
		Competitive struct {
			AverageStats struct {
			} `json:"average_stats"`
			GameStats struct {
				Kpd                         float64 `json:"kpd"`
				SoloKillsMostInGame         float64 `json:"solo_kills_most_in_game"`
				TurretsDestroyedMostInGame  float64 `json:"turrets_destroyed_most_in_game"`
				HeroDamageDoneMostInGame    float64 `json:"hero_damage_done_most_in_game"`
				FinalBlows                  float64 `json:"final_blows"`
				Multikills                  float64 `json:"multikills"`
				DefensiveAssists            float64 `json:"defensive_assists"`
				MedalsSilver                float64 `json:"medals_silver"`
				HeroDamageDone              float64 `json:"hero_damage_done"`
				MedalsBronze                float64 `json:"medals_bronze"`
				HealingDone                 float64 `json:"healing_done"`
				Cards                       float64 `json:"cards"`
				OffensiveAssists            float64 `json:"offensive_assists"`
				Deaths                      float64 `json:"deaths"`
				TurretsDestroyed            float64 `json:"turrets_destroyed"`
				SoloKills                   float64 `json:"solo_kills"`
				MedalsGold                  float64 `json:"medals_gold"`
				GamesTied                   float64 `json:"games_tied"`
				ObjectiveTimeMostInGame     float64 `json:"objective_time_most_in_game"`
				ObjectiveKillsMostInGame    float64 `json:"objective_kills_most_in_game"`
				MeleeFinalBlowsMostInGame   float64 `json:"melee_final_blows_most_in_game"`
				MultikillBest               float64 `json:"multikill_best"`
				KillStreakBest              float64 `json:"kill_streak_best"`
				GamesLost                   float64 `json:"games_lost"`
				TimeSpentOnFireMostInGame   float64 `json:"time_spent_on_fire_most_in_game"`
				EnvironmentalKills          float64 `json:"environmental_kills"`
				GamesWon                    float64 `json:"games_won"`
				ObjectiveKills              float64 `json:"objective_kills"`
				AllDamageDone               float64 `json:"all_damage_done"`
				TimeSpentOnFire             float64 `json:"time_spent_on_fire"`
				GamesPlayed                 float64 `json:"games_played"`
				OffensiveAssistsMostInGame  float64 `json:"offensive_assists_most_in_game"`
				BarrierDamageDoneMostInGame float64 `json:"barrier_damage_done_most_in_game"`
				Eliminations                float64 `json:"eliminations"`
				TimePlayed                  float64 `json:"time_played"`
				MeleeFinalBlows             float64 `json:"melee_final_blows"`
				AllDamageDoneMostInGame     float64 `json:"all_damage_done_most_in_game"`
				BarrierDamageDone           float64 `json:"barrier_damage_done"`
				EnvironmentalKillMostInGame float64 `json:"environmental_kill_most_in_game"`
				HealingDoneMostInGame       float64 `json:"healing_done_most_in_game"`
				DefensiveAssistsMostInGame  float64 `json:"defensive_assists_most_in_game"`
				ObjectiveTime               float64 `json:"objective_time"`
				FinalBlowsMostInGame        float64 `json:"final_blows_most_in_game"`
				EliminationsMostInGame      float64 `json:"eliminations_most_in_game"`
				Medals                      float64 `json:"medals"`
			} `json:"game_stats"`
			Competitive         bool `json:"competitive"`
			RollingAverageStats struct {
				ObjectiveKills    float64 `json:"objective_kills"`
				SoloKills         float64 `json:"solo_kills"`
				HeroDamageDone    float64 `json:"hero_damage_done"`
				AllDamageDone     float64 `json:"all_damage_done"`
				HealingDone       float64 `json:"healing_done"`
				TimeSpentOnFire   float64 `json:"time_spent_on_fire"`
				Eliminations      float64 `json:"eliminations"`
				ObjectiveTime     float64 `json:"objective_time"`
				BarrierDamageDone float64 `json:"barrier_damage_done"`
				Deaths            float64 `json:"deaths"`
				FinalBlows        float64 `json:"final_blows"`
			} `json:"rolling_average_stats"`
			OverallStats struct {
				Ties      int     `json:"ties"`
				Wins      int     `json:"wins"`
				Level     int     `json:"level"`
				Losses    int     `json:"losses"`
				Tier      string  `json:"tier"`
				RankImage string  `json:"rank_image"`
				Prestige  int     `json:"prestige"`
				Comprank  int     `json:"comprank"`
				Avatar    string  `json:"avatar"`
				WinRate   float64 `json:"win_rate"`
				Games     int     `json:"games"`
			} `json:"overall_stats"`
		} `json:"competitive"`
	} `json:"stats"`
}
